BEGIN;

DROP TABLE IF EXISTS ad_source_purchase CASCADE;
DROP TABLE IF EXISTS click_reward CASCADE;
DROP TABLE IF EXISTS referral_reward CASCADE;
DROP TABLE IF EXISTS balance_transaction CASCADE;
DROP TABLE IF EXISTS click CASCADE;
DROP TABLE IF EXISTS link CASCADE;
DROP TABLE IF EXISTS ad_source CASCADE;
DROP TABLE IF EXISTS person CASCADE;

DROP TYPE IF EXISTS ad_type;
DROP TYPE IF EXISTS click_status;

COMMIT;
