http_server:
  write_timeout: 10s
  read_header_timeout: 3s
  read_timeout: 15s
  idle_timeout: 60s

service:
  generated_alias_length: 4
  tries_to_generate: 5
  alp: "abc123"

auth:
  jwt_secret: "secret"
  user_id_jwt_key: "user_id"
  user_id_cookie_name: "user_id"






